import re
def str2emoji(tweet):
	tweet = re.sub(r":‑\)"," ☺️ ",tweet)
	tweet = re.sub(r":\)"," ☺️ ",tweet)
	tweet = re.sub(r":-\]"," ☺️ ",tweet)
	tweet = re.sub(r":\]"," ☺️ ",tweet)
	tweet = re.sub(r":-3"," ☺️ ",tweet)
	tweet = re.sub(r":3","  ☺️ ",tweet)
	tweet = re.sub(r":->"," ☺️ ",tweet)
	tweet = re.sub(r"</3",' 💔 ',tweet)
	tweet = re.sub(r"<3"," ❤️ ",tweet)
	tweet = re.sub(r":>"," ☺️ ",tweet)
	tweet = re.sub(r"8-\)"," ☺️ ",tweet)
	tweet = re.sub(r":o\)"," ☺️ ",tweet)
	tweet = re.sub(r":-\}"," ☺️ ",tweet)
	tweet = re.sub(r":\}"," ☺️ ",tweet)
	tweet = re.sub(r":-\)"," ☺️ ",tweet)
	tweet = re.sub(r":c\)"," ☺️ ",tweet)
	tweet = re.sub(r":\^\)"," ☺️ ",tweet)
	tweet = re.sub(r"=\]"," ☺️ ",tweet)
	tweet = re.sub(r"=\)"," ☺️ ",tweet)
	tweet = re.sub(r":‑D"," 😃 ",tweet)
	tweet = re.sub(r":D"," 😃 ",tweet)
	tweet = re.sub(r"8‑D"," 😃 ",tweet)
	tweet = re.sub(r"8D"," 😃 ",tweet)
	tweet = re.sub(r"X‑D"," 😃 ",tweet)
	tweet = re.sub(r"XD"," 😃 ",tweet)
	tweet = re.sub(r"=D"," 😃 ",tweet)
	tweet = re.sub(r"=3"," 😃 ",tweet)
	tweet = re.sub(r"B\^D"," 😃 ",tweet)
	tweet = re.sub(r":-\)\)"," 😃 ",tweet)
	tweet = re.sub(r":‑\("," ☹️ ",tweet)
	tweet = re.sub(r":-\("," ☹️ ",tweet)



	tweet = re.sub(r":\("," ☹️ ",tweet)
	tweet = re.sub(r":‑c"," ☹️ ",tweet)
	tweet = re.sub(r":c"," ☹️ ",tweet)
	tweet = re.sub(r":‑<"," ☹️ ",tweet)
	tweet = re.sub(r":<"," ☹️ ",tweet)
	tweet = re.sub(r":‑\["," ☹️ ",tweet)
	tweet = re.sub(r":\["," ☹️ ",tweet)
	tweet = re.sub(r":-\|\|"," ☹️ ",tweet)
	tweet = re.sub(r">:\["," ☹️ ",tweet)
	tweet = re.sub(r":\{"," ☹️ ",tweet)
	tweet = re.sub(r":@"," ☹️ ",tweet)
	tweet = re.sub(r">:\("," ☹️ ",tweet)
	tweet = re.sub(r":'‑\("," 😭 ",tweet)
	tweet = re.sub(r":'\("," 😭 ",tweet)
	tweet = re.sub(r":'‑\)"," 😃 ",tweet)
	tweet = re.sub(r":'\)"," 😃 ",tweet)
	tweet = re.sub(r"D‑':"," 😧 ",tweet)
	tweet = re.sub(r"D:<"," 😨 ",tweet)
	tweet = re.sub(r"D:"," 😧 ",tweet)
	tweet = re.sub(r"D8"," 😧 ",tweet)
	tweet = re.sub(r"D;"," 😧 ",tweet)
	tweet = re.sub(r"D="," 😧 ",tweet)
	tweet = re.sub(r"DX"," 😧 ",tweet)
	tweet = re.sub(r":‑O"," 😮 ",tweet)
	tweet = re.sub(r":O"," 😮 ",tweet)
	tweet = re.sub(r":‑o"," 😮 ",tweet)
	tweet = re.sub(r":o"," 😮 ",tweet)
	tweet = re.sub(r":-0"," 😮 ",tweet)
	tweet = re.sub(r"8‑0"," 😮 ",tweet)
	tweet = re.sub(r">:O"," 😮 ",tweet)
	tweet = re.sub(r":-\*"," 😗 ",tweet)
	tweet = re.sub(r":\*"," 😗 ",tweet)
	tweet = re.sub(r":X"," 😗 ",tweet)
	tweet = re.sub(r";‑\)"," 😉 ",tweet)
	tweet = re.sub(r";\)"," 😉 ",tweet)
	tweet = re.sub(r"\*-\)"," 😉 ",tweet)
	tweet = re.sub(r"\*\)"," 😉 ",tweet)
	tweet = re.sub(r";‑\]"," 😉 ",tweet)
	tweet = re.sub(r";\]"," 😉 ",tweet)
	tweet = re.sub(r";\^\)"," 😉 ",tweet)
	tweet = re.sub(r":‑,"," 😉 ",tweet)
	tweet = re.sub(r";D"," 😉 ",tweet)
	tweet = re.sub(r":‑P"," 😛 ",tweet)
	tweet = re.sub(r":‑p"," 😛 ",tweet)
	tweet = re.sub(r":P"," 😛 ",tweet)
	tweet = re.sub(r":p"," 😛 ",tweet)
	tweet = re.sub(r"X‑P"," 😛 ",tweet)
	tweet = re.sub(r"XP"," 😛 ",tweet)
	tweet = re.sub(r"xp"," 😛 ",tweet)
	tweet = re.sub(r":‑Þ"," 😛 ",tweet)
	tweet = re.sub(r":Þ"," 😛 ",tweet)
	tweet = re.sub(r":b"," 😛 ",tweet)
	tweet = re.sub(r"d:"," 😛 ",tweet)
	tweet = re.sub(r"=p"," 😛 ",tweet)
	tweet = re.sub(r">:P"," 😛 ",tweet)
	tweet = re.sub(r":‑/"," 😕 ",tweet)
	tweet = re.sub(r":/"," 😕 ",tweet)
	tweet = re.sub(r":-\[\.\]"," 😕 ",tweet)
	tweet = re.sub(r">:/"," 😕 ",tweet)
	tweet = re.sub(r"=/"," 😕 ",tweet)
	tweet = re.sub(r":L"," 😕 ",tweet)
	tweet = re.sub(r"=L"," 😕 ",tweet)
	tweet = re.sub(r":S"," 😕 ",tweet)
	tweet = re.sub(r":‑\|"," 😐 ",tweet)
	tweet = re.sub(r":\|"," 😐 ",tweet)
	tweet = re.sub(r":$"," 😳 ",tweet)
	tweet = re.sub(r":‑x"," 🤐 ",tweet)
	tweet = re.sub(r":x"," 🤐 ",tweet)
	tweet = re.sub(r":‑#"," 🤐 ",tweet)
	tweet = re.sub(r":#"," 🤐 ",tweet)
	tweet = re.sub(r":‑&"," 🤐 ",tweet)
	tweet = re.sub(r":&"," 🤐 ",tweet)
	tweet = re.sub(r"O:‑\)"," 😇 ",tweet)
	tweet = re.sub(r"O:\)"," 😇 ",tweet)
	tweet = re.sub(r"0:‑3"," 😇 ",tweet)
	tweet = re.sub(r"0:3"," 😇 ",tweet)
	tweet = re.sub(r"0:‑\)"," 😇 ",tweet)
	tweet = re.sub(r"0:\)"," 😇 ",tweet)
	tweet = re.sub(r":‑b"," 😛 ",tweet)
	tweet = re.sub(r"0;\^\)"," 😇 ",tweet)
	tweet = re.sub(r">:‑\)"," 😈 ",tweet)
	tweet = re.sub(r">:\)"," 😈 ",tweet)
	tweet = re.sub(r"\}:‑\)"," 😈 ",tweet)
	tweet = re.sub(r"\}:\)"," 😈 ",tweet)
	tweet = re.sub(r"3:‑\)"," 😈 ",tweet)
	tweet = re.sub(r"3:\)"," 😈 ",tweet)
	tweet = re.sub(r">;\)"," 😈 ",tweet)
	tweet = re.sub(r"\|;‑\)"," 😎 ",tweet)
	tweet = re.sub(r"\|‑O"," 😏 ",tweet)
	tweet = re.sub(r":‑J"," 😏 ",tweet)
	tweet = re.sub(r"%‑\)"," 😵 ",tweet)
	tweet = re.sub(r"%\)"," 😵 ",tweet)
	tweet = re.sub(r":-###.."," 🤒 ",tweet)
	tweet = re.sub(r":###.."," 🤒 ",tweet)
	tweet = re.sub(r"\(>_<\)"," 😣 ",tweet)
	tweet = re.sub(r"\(>_<\)>"," 😣 ",tweet)
	tweet = re.sub(r"\(';'\)"," 👶 ",tweet)
	tweet = re.sub(r"\(\^\^>``"," 😓 ",tweet)
	tweet = re.sub(r"\(\^_\^;\)"," 😓 ",tweet)
	tweet = re.sub(r"\(-_-;\)"," 😓 ",tweet)
	tweet = re.sub(r"\(~_~;\) \(・\.・;\)"," 😓 ",tweet)
	tweet = re.sub(r"\(-_-\)zzz"," 😴 ",tweet)
	tweet = re.sub(r"\(\^_-\)"," 😉 ",tweet)
	tweet = re.sub(r"\(\(\+_\+\)\)"," 😕 ",tweet)
	tweet = re.sub(r"\(\+o\+\)"," 😕 ",tweet)
	tweet = re.sub(r"\^_\^"," 😃 ",tweet)
	tweet = re.sub(r"\(\^_\^\)/"," 😃 ",tweet)
	tweet = re.sub(r"\(\^O\^\)／"," 😃 ",tweet)
	tweet = re.sub(r"\(\^o\^\)／"," 😃 ",tweet)
	tweet = re.sub(r"\(__\)"," 🙇 ",tweet)
	tweet = re.sub(r"_\(\._\.\)_"," 🙇 ",tweet)
	tweet = re.sub(r"<\(_ _\)>"," 🙇 ",tweet)
	tweet = re.sub(r"<m\(__\)m>"," 🙇 ",tweet)
	tweet = re.sub(r"m\(__\)m"," 🙇 ",tweet)
	tweet = re.sub(r"m\(_ _\)m"," 🙇 ",tweet)
	tweet = re.sub(r"\('_'\)"," 😭 ",tweet)
	tweet = re.sub(r"\(/_;\)"," 😭 ",tweet)
	tweet = re.sub(r"\(T_T\) \(;_;\)"," 😭 ",tweet)
	tweet = re.sub(r"\(;_;"," 😭 ",tweet)
	tweet = re.sub(r"\(;_:\)"," 😭 ",tweet)
	tweet = re.sub(r"\(;O;\)"," 😭 ",tweet)
	tweet = re.sub(r"\(:_;\)"," 😭 ",tweet)
	tweet = re.sub(r"\(ToT\)"," 😭 ",tweet)
	tweet = re.sub(r";_;"," 😭 ",tweet)
	tweet = re.sub(r";-;"," 😭 ",tweet)
	tweet = re.sub(r";n;"," 😭 ",tweet)
	tweet = re.sub(r";;"," 😭 ",tweet)
	tweet = re.sub(r"Q\.Q"," 😭 ",tweet)
	tweet = re.sub(r"T\.T"," 😭 ",tweet)
	tweet = re.sub(r"QQ"," 😭 ",tweet)
	tweet = re.sub(r"Q_Q"," 😭 ",tweet)
	tweet = re.sub(r"\(-\.-\)"," 😞 ",tweet)
	tweet = re.sub(r"\(-_-\)"," 😞 ",tweet)
	tweet = re.sub(r"\(一一\)"," 😞 ",tweet)
	tweet = re.sub(r"\(；一_一\)"," 😞 ",tweet)
	tweet = re.sub(r"\(=_=\)"," 😩 ",tweet)
	tweet = re.sub(r"\(=\^\·\^=\)"," 😺 ",tweet)
	tweet = re.sub(r"\(=\^\·\·\^=\)"," 😺 ",tweet)
	tweet = re.sub(r"=_\^= "," 😺 ",tweet)
	tweet = re.sub(r"\(\.\.\)"," 😔 ",tweet)
	tweet = re.sub(r"\(\._\.\)"," 😔 ",tweet)
	tweet = re.sub(r"\(\・\・\?"," 😕 ",tweet)
	tweet = re.sub(r"\(\?_\?\)"," 😕 ",tweet)
	tweet = re.sub(r">\^_\^<"," 😃 ",tweet)
	tweet = re.sub(r"<\^!\^>"," 😃 ",tweet)
	tweet = re.sub(r"\^/\^"," 😃 ",tweet)
	tweet = re.sub(r"\（\*\^_\^\*）"," 😃 ",tweet)
	tweet = re.sub(r"\(\^<\^\) \(\^\.\^\)"," 😃 ",tweet)
	tweet = re.sub(r"\(^\^\)"," 😃 ",tweet)
	tweet = re.sub(r"\(\^\.\^\)"," 😃 ",tweet)
	tweet = re.sub(r"\(\^_\^\.\)"," 😃 ",tweet)
	tweet = re.sub(r"\(\^_\^\)"," 😃 ",tweet)
	tweet = re.sub(r"\(\^\^\)"," 😃 ",tweet)
	tweet = re.sub(r"\(\^J\^\)"," 😃 ",tweet)
	tweet = re.sub(r"\(\*\^\.\^\*\)"," 😃 ",tweet)
	tweet = re.sub(r"\(\^—\^\）"," 😃 ",tweet)
	tweet = re.sub(r"\(#\^\.\^#\)"," 😃 ",tweet)
	tweet = re.sub(r"\（\^—\^\）"," 👋 ",tweet)
	tweet = re.sub(r"\(;_;\)/~~~"," 👋 ",tweet)
	tweet = re.sub(r"\(\^\.\^\)/~~~"," 👋 ",tweet)
	tweet = re.sub(r"\(T_T\)/~~~"," 👋 ",tweet)
	tweet = re.sub(r"\(ToT\)/~~~"," 👋 ",tweet)
	tweet = re.sub(r"\(\*\^0\^\*\)"," 😍 ",tweet)
	tweet = re.sub(r"\(\*_\*\)"," 😍 ",tweet)
	tweet = re.sub(r"\(\*_\*;"," 😍 ",tweet)
	tweet = re.sub(r"\(\+_\+\) \(@_@\)"," 😍 ",tweet)
	tweet = re.sub(r"\(\*\^\^\)v"," 😂 ",tweet)
	tweet = re.sub(r"\(\^_\^\)v"," 😂 ",tweet)
	tweet = re.sub(r"\(ーー;\)"," 😓 ",tweet)
	tweet = re.sub(r"\(\^0_0\^\)"," 😎 ",tweet)
	tweet = re.sub(r"\(\＾ｖ\＾\)"," 😀 ",tweet)
	tweet = re.sub(r"\(\＾ｕ\＾\)"," 😀 ",tweet)
	tweet = re.sub(r"\(\^\)o\(\^\)"," 😀 ",tweet)
	tweet = re.sub(r"\(\^O\^\)"," 😀 ",tweet)
	tweet = re.sub(r"\(\^o\^\)"," 😀 ",tweet)
	tweet = re.sub(r"\)\^o\^\("," 😀 ",tweet)
	tweet = re.sub(r":O o_O"," 😮 ",tweet)
	tweet = re.sub(r"o_0"," 😮 ",tweet)
	tweet = re.sub(r"o\.O"," 😮 ",tweet)
	tweet = re.sub(r"\(o\.o\)"," 😮 ",tweet)
	tweet = re.sub(r"oO"," 😮 ",tweet)
	tweet = re.sub(r':\‑\)','😃',tweet)
	tweet = re.sub(r":\)"," ☺️ ",tweet)
	tweet = re.sub(r":-]"," ☺️ ",tweet)
	tweet = re.sub(r":]"," ☺️ ",tweet)
	tweet = re.sub(r"8\-\)"," ☺️ ",tweet)
	tweet = re.sub(r":o\)"," ☺️ ",tweet)
	tweet = re.sub(r":-}"," ☺️ ",tweet)
	tweet = re.sub(r":}"," ☺️ ",tweet)
	tweet = re.sub(r":\-\)"," ☺️ ",tweet)
	tweet = re.sub(r":c\)"," ☺️ ",tweet)
	tweet = re.sub(r":^\)"," ☺️ ",tweet)
	tweet = re.sub(r"=]"," ☺️ ",tweet)
	tweet = re.sub(r"=\)"," ☺️ ",tweet)
	tweet = re.sub(r"B^D"," 😃 ",tweet)
	tweet = re.sub(r":-\)\)"," 😃 ",tweet)
	tweet = re.sub(r":-\("," ☹️ ",tweet)

	tweet = re.sub(r":‑\("," ☹️ ",tweet)
	tweet = re.sub(r":\("," ☹️ ",tweet)
	tweet = re.sub(r":\‑\["," ☹️ ",tweet)
	tweet = re.sub(r":\["," ☹️ ",tweet)
	tweet = re.sub(r":-\|\|"," ☹️ ",tweet)
	tweet = re.sub(r">\:\["," ☹️ ",tweet)
	tweet = re.sub(r":{"," ☹️ ",tweet)
	tweet = re.sub(r">\:\("," ☹️ ",tweet)
	tweet = re.sub(r":'‑\("," 😭 ",tweet)
	tweet = re.sub(r":'\("," 😭 ",tweet)
	tweet = re.sub(r":'\‑\)"," 😃 ",tweet)
	tweet = re.sub(r":'\)"," 😃 ",tweet)
	tweet = re.sub(r":-\*"," 😗 ",tweet)
	tweet = re.sub(r":\*"," 😗 ",tweet)
	tweet = re.sub(r";\‑\)"," 😉 ",tweet)
	tweet = re.sub(r";\)"," 😉 ",tweet)
	tweet = re.sub(r"\*\-\)"," 😉 ",tweet)
	tweet = re.sub(r"\*\)"," 😉 ",tweet)
	tweet = re.sub(r";‑\]"," 😉 ",tweet)
	tweet = re.sub(r";\]"," 😉 ",tweet)
	tweet = re.sub(r";^\)"," 😉 ",tweet)
	tweet = re.sub(r">\:\[\(\)\]"," 😕 ",tweet)

	tweet = re.sub(r":\[\(\)\]"," 😕 ",tweet)
	tweet = re.sub(r"=\[\(\)\]"," 😕 ",tweet)
	tweet = re.sub(r":‑\|"," 😐 ",tweet)
	tweet = re.sub(r":\|"," 😐 ",tweet)
	tweet = re.sub(r"O:‑\)"," 😇 ",tweet)
	tweet = re.sub(r"O:\)"," 😇 ",tweet)
	tweet = re.sub(r"0:‑\)"," 😇 ",tweet)
	tweet = re.sub(r"0:\)"," 😇 ",tweet)
	tweet = re.sub(r"0;^\)"," 😇 ",tweet)
	tweet = re.sub(r">:‑\)"," 😈 ",tweet)
	tweet = re.sub(r">:\)"," 😈 ",tweet)
	tweet = re.sub(r"}:‑\)"," 😈 ",tweet)
	tweet = re.sub(r"}:\)"," 😈 ",tweet)
	tweet = re.sub(r"3:‑\)"," 😈 ",tweet)
	tweet = re.sub(r"3:\)"," 😈 ",tweet)
	tweet = re.sub(r">;\)"," 😈 ",tweet)
	tweet = re.sub(r"\|;‑\)"," 😎 ",tweet)
	tweet = re.sub(r"\|‑O"," 😏 ",tweet)
	tweet = re.sub(r"%‑\)"," 😵 ",tweet)
	tweet = re.sub(r"%\)"," 😵 ",tweet)
	tweet = re.sub(r"\(>_<\)"," 😣 ",tweet)
	tweet = re.sub(r"\(>_<\)>"," 😣 ",tweet)
	tweet = re.sub(r"\(';'\)"," Baby ",tweet)
	tweet = re.sub(r"\(^^>``"," 😓 ",tweet)
	tweet = re.sub(r"\(^_^;\)"," 😓 ",tweet)
	tweet = re.sub(r"\(-_-;\)"," 😓 ",tweet)

	tweet = re.sub(r"\(~_~;\) \(・\.・;\)"," 😓 ",tweet)
	tweet = re.sub(r"\(-_-\)zzz"," 😴 ",tweet)
	tweet = re.sub(r"\(^_-\)"," 😉 ",tweet)
	tweet = re.sub(r"\(\(\+_\+\)\)"," 😕 ",tweet)
	tweet = re.sub(r"\(\+o\+\)"," 😕 ",tweet)
	tweet = re.sub(r"^_^"," 😃 ",tweet)
	tweet = re.sub(r"\(^_^\)/"," 😃 ",tweet)
	tweet = re.sub(r"\(^O^\)／"," 😃 ",tweet)
	tweet = re.sub(r"\(^o^\)／"," 😃 ",tweet)
	tweet = re.sub(r"\(__\)"," 🙇 ",tweet)
	tweet = re.sub(r"_\(._.\)_"," 🙇 ",tweet)
	tweet = re.sub(r"<\(_ _\)>"," 🙇 ",tweet)
	tweet = re.sub(r"<m\(__\)m>"," 🙇 ",tweet)
	tweet = re.sub(r"m\(__\)m"," 🙇 ",tweet)
	tweet = re.sub(r"m\(_ _\)m"," 🙇 ",tweet)
	tweet = re.sub(r"\('_'\)"," 😭 ",tweet)
	tweet = re.sub(r"\(/_;\)"," 😭 ",tweet)
	tweet = re.sub(r"\(T_T\) (;_;)"," 😭 ",tweet)
	tweet = re.sub(r"\(;_;"," 😭 ",tweet)
	tweet = re.sub(r"\(;_:\)"," 😭 ",tweet)
	tweet = re.sub(r"\(;O;\)"," 😭 ",tweet)
	tweet = re.sub(r"\(:_;\)"," 😭 ",tweet)
	tweet = re.sub(r"\(ToT\)","  😭  ",tweet)
	tweet = re.sub(r"Q\.Q"," 😭 ",tweet)
	tweet = re.sub(r"T\.T"," 😭 ",tweet)
	tweet = re.sub(r"\(-\.-\)"," 😞 ",tweet)
	tweet = re.sub(r"\(-_-\)"," 😞 ",tweet)

	tweet = re.sub(r"\(一一\)"," 😞 ",tweet)
	tweet = re.sub(r"\(；一_一\)"," 😞 ",tweet)

	tweet = re.sub(r"\(=\_=\)"," 😩 ",tweet)
	tweet = re.sub(r"\(=^\·^=\)"," 😺 ",tweet)
	
	tweet = re.sub(r"\(=^··^=\)"," 😺 ",tweet)
	tweet = re.sub(r"=_^= "," 😺 ",tweet)

	tweet = re.sub(r"\(\.\.\)"," 😔 ",tweet)

	tweet = re.sub(r"\(\._\.\)"," 😔  ",tweet)
	tweet = re.sub(r"\(・・\?"," 😕 ",tweet)
	tweet = re.sub(r"\(\?_\?\)"," 😕 ",tweet)

	tweet = re.sub(r">^_^<"," 😃 ",tweet)
	tweet = re.sub(r"<^\!^>"," 😃 ",tweet)
	tweet = re.sub(r"^/^","  😃  ",tweet)
	tweet = re.sub(r"\(\*^_^\*\)","  😃  ",tweet)
	tweet = re.sub(r"\(^^\)","  😃  ",tweet)
	tweet = re.sub(r"\(^\.^\)","  😃  ",tweet)
	tweet = re.sub(r"\(^_^\.\)","  😃  ",tweet)
	tweet = re.sub(r"\(^_^\)","  😃  ",tweet)
	tweet = re.sub(r"\(^J^\)","  😃  ",tweet)
	tweet = re.sub(r"\(\*^\.^\*\)"," 😃  ",tweet)
	tweet = re.sub(r"\(^—^\）"," 😃 ",tweet)

	tweet = re.sub(r"\(#^.^#\)"," 😃 ",tweet)
	tweet = re.sub(r"\(^—^\)"," 👋 ",tweet)
	tweet = re.sub(r"\(;_;\)/~~~","  👋  ",tweet)

	tweet = re.sub(r"\(^.^\)/~~~"," 👋 ",tweet)
	tweet = re.sub(r"\(-_-\)/~~~ \($··\)/~~~"," 👋 ",tweet)
	tweet = re.sub(r"\(T_T\)/~~~"," 👋 ",tweet)

	tweet = re.sub(r"\(ToT\)/~~~"," 👋 ",tweet)
	tweet = re.sub(r"\(\*^0^\*\)"," 😍 ",tweet)
	tweet = re.sub(r"\(\*_\*\)"," 😍 ",tweet)

	tweet = re.sub(r"\(\*_\*;"," 😍 ",tweet)
	tweet = re.sub(r"\(+_+\) \(@_@\)"," 😍 ",tweet)
	tweet = re.sub(r"o\.O"," 😮 ",tweet)
	tweet = re.sub(r"\(o\.o\)"," 😮 ",tweet)


	return tweet
#print(str2emoji("Sorry exams going on	oh :) hows it going?	Sad life"))
